### ISSUE TITLE
Routes - Part 1

### ISSUE THREAD

**Issue by jalynnlim** [ishidas/trunks-of-seattle#7]
GET/POST    /trees
GET/PUT/DELETE  /trees/:tree
GET/PUT/DELETE  /trees/species/:species
GET/PUT/DELETE  /trees/species/:species/neighborhoods/:neighborhood

**Comment by ishidas** [comment]
Completed routes and tests for routes. Got rid of PUT/DELETE /trees/species/:species and pending on GET/PUT/DELETE /trees/species/:species/neighborhoods/:neighborhood routes.
